config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]
  as :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    get 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'
  get 'home/index'
  root 'home#index'

  resources :users, only: [:index, :show, :destroy]
  resources :foods, only: [:new, :create, :index, :destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
      get :shopping_list
    end
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'general_shopping_lists', to: 'shopping_lists#index', as: 'general_shopping_lists'
end

app/models/application_record.rb
# comment
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
# comment
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
end

app/models/recipe.rb
# comment
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
end

app/models/recipe_food.rb
# comment
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  after_initialize :set_default_quantity

  def set_default_quantity
    puts 'Setting default quantity'
    self.quantity ||= 1
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes
  has_many :foods

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def index
    @foods = current_user.foods.all
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food was successfully deleted.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe

    if @recipe_food.save
      flash[:notice] = 'Ingredient added successfully'
      redirect_to @recipe
    else
      flash[:alert] = 'Ingredient failed to add'
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.update(recipe_food_params)
      flash[:notice] = 'Ingredient updated successfully'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = 'Ingredient failed to update'
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.destroy
      flash[:notice] = 'Ingredient deleted successfully'
    else
      flash[:alert] = 'Ingredient failed to delete'
    end

    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def public_recipes
    @recipes = Recipe.includes(:user, :foods).where(public: true).order(created_at: :desc)
  end

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @user = current_user
    @recipe_foods = @recipe.recipe_foods
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:notice] = 'Recipe saved successfully'
    else
      flash[:alert] = 'Recipe failed to save'
    end
    redirect_to recipes_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully'
    else
      flash[:alert] = 'Error!, No recipe was deleted'
    end
    redirect_to recipes_path
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
    @general_food_list = @user.foods
    @missing_food_items = calculate_missing_food_items(@recipes, @general_food_list)
    @total_missing_items = @missing_food_items.values.sum
    @total_missing_price = calculate_total_missing_price(@missing_food_items)

    @general_shopping_list = generate_general_shopping_list(@missing_food_items, @general_food_list)
    @total_food_items = @general_shopping_list.sum { |item| item[:quantity] }
    @total_price = @general_shopping_list.sum { |item| item[:quantity] * item[:price] }
  end

  private

  # Calculate missing food items by comparing the recipes' food items with the general food list
  def calculate_missing_food_items(recipes, general_food_list)
    missing_food_items = Hash.new(0)

    recipes.each do |recipe|
      recipe.foods.each do |food|
        general_quantity = general_food_list.find_by(name: food.name)&.quantity || 0
        missing_quantity = [food.quantity - general_quantity, 0].max
        missing_food_items[food.name] += missing_quantity
      end
    end

    missing_food_items
  end

  # Calculate the total price of missing food items
  def calculate_total_missing_price(missing_food_items)
    total_price = 0

    missing_food_items.each do |food_name, quantity|
      food = current_user.foods.find_by(name: food_name)
      total_price += food.price * quantity if food
    end
    total_price
  end

  def generate_general_shopping_list(missing_food_items, general_food_list)
    general_shopping_list = []

    missing_food_items.each do |food_name, quantity|
      food = general_food_list.find_by(name: food_name)
      next unless food

      general_shopping_list << {
        name: food_name,
        quantity:,
        price: food.price
      }
    end

    general_food_list
  end
end

app/helpers/application_helper.rb
# comment
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/foods/index.html.erb
<div class="text-center mt-4 mb-4">
  <%= link_to 'Add Food', new_food_path, class: 'btn btn-primary' %>
</div>
<table class="table table-bordered table-striped" style="width: 500px; margin: auto;">
  <thead class="thead-dark">
    <tr>
      <th>Food</th>
      <th>Measurement unit</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Delete', food_path(food), data: { turbo_method: :delete }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
        <h2>New Food</h2>
      <%= form_with model: @food, local: true, html: { class: 'form-group' } do |form| %>

        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :measurement_unit, class: 'form-label' %>
          <%= form.text_field :measurement_unit, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :price, class: 'form-label' %>
          <%= form.number_field :price, step: 0.01, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :quantity, class: 'form-label' %>
          <%= form.number_field :quantity, step: 0.01, class: 'form-control' %>
        </div>

        <%= form.submit 'Create Food', class: 'btn btn-primary' %>

      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= image_tag 'banner.jpg', alt: 'Banner', style: 'width: 100%;' %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white py-4">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6">
        <h5>Recipe App</h5>
        <p>An app for all your favorite recipes.</p>
      </div>
      <div class="col-12 col-md-6">
        <h5>Contact</h5>
        <ul class="list-unstyled">
          <li><a href="#" class="text-white">Twitter</a></li>
          <li><a href="#" class="text-white">Facebook</a></li>
          <li><a href="#" class="text-white">Instagram</a></li>
        </ul>
      </div>
    </div>
    <hr class="bg-white">
    <div class="row">
      <div class="col text-center">
        <p>Application created by: Wilhelm Kamulunga & Marco Díaz </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= image_tag 'logo.png', alt: 'RecipeApp', class: 'navbar-logo' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Home', '/', class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Public Recipes', public_recipes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Personal Recipes', recipes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Shopping List', general_shopping_lists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Foods', foods_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %> 
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<%= form_with(model: [@recipe, @recipe_food], local: true) do |form| %>
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
    
    <%= form.submit 'Update' %>
<% end %>

app/views/recipe_foods/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Add Ingredient to Recipe</h2>
     <%= form_with(model: [@recipe, @recipe_food], local: true, html: { class: 'form-group' }) do |form| %>
  <div class="mb-3">
    <%= form.label :food_id, 'Food' %>
    <%= form.collection_select :food_id, Food.all, :id, :name, {}, { class: 'form-control' } %>
  </div>

  <div class="mb-3">
    <%= form.label :quantity, class: 'form-label' %>
    <%= form.number_field :quantity, step: 0.01, class: 'form-control' %>
  </div>

  <%= form.submit 'Add Ingredient to Recipe', class: 'btn btn-primary' %>
<% end %>

    </div>
  </div>
</div>

app/views/recipes/_add_ingredient_to_recipe_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>Add Ingredient to Recipe</h2>
      <%= form_with(model: [@recipe, @recipe_food], local: true, html: { class: 'form-group' }) do |form| %>
        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :measurement_unit, class: 'form-label' %>
          <%= form.text_field :measurement_unit, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :price, class: 'form-label' %>
          <%= form.number_field :price, step: 0.01, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= form.label :quantity, class: 'form-label' %>
          <%= form.number_field :quantity, step: 0.01, class: 'form-control' %>
        </div>

        <%= form.submit 'Add Ingredient to Recipe', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_recipe_food_form.html.erb
<% if @recipe.user == current_user %>
  <%= render 'recipe_food_form' %>
<% end %>

app/views/recipes/index.html.erb
<h1>Your Recipes</h1>

<div class="recipes">
  <%= link_to 'New recipe', new_recipe_path, class: 'btn btn-primary mb-4' %>
  
  <% @recipes.each do |recipe| %>
    <div class="recipe-box d-flex justify-content-between align-items-center">
      <div class="left-column">
        <h2>
          <%= link_to recipe.name, recipe_path(recipe) %>
        </h2>
        <%= button_to 'REMOVE', recipe_path(recipe), method: :delete, class: 'btn btn-danger btn-sm mt-3', data: { confirm: 'Are you sure?' } %>
      </div>
      <div class="right-column">
        <p><%= recipe.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2>New Recipe</h2>
      <%= form_with(model: @recipe, local: true, html: { class: 'form-group' }) do |f| %>
        
        <div class="mb-3">
          <%= f.label :name, "Name", class: 'form-label' %>
          <%= f.text_field :name, placeholder: "Recipe name", class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.label :preparation_time, "Preparation time", class: 'form-label' %>
          <%= f.text_field :preparation_time, placeholder: "10", class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.label :cooking_time, "Cooking time", class: 'form-label' %>
          <%= f.text_field :cooking_time, placeholder: "20", class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.label :description, "Description", class: 'form-label' %>
          <%= f.text_field :description, placeholder: "Recipe description", class: 'form-control' %>
        </div>
        
        <div class="mb-3">
          <%= f.submit "Submit", class: 'btn btn-primary' %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes</h1>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe-box">
      <div class="left-column">
        <h2><%= recipe.name %></h2>
        <p>by <%= recipe.user.name %></p>
      </div>
      <div class="right-column">
        <p>Total food items: <%= recipe.foods.count %></p>
        <p>Total price: <%= recipe.foods.sum(&:price) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1 class="text-center text-muted my-4"><%= @recipe.name %></h1>

  <div class="row justify-content-between align-items-center">
    <div class="col-md-4">
      <p class="text-dark"><strong>Preparation Time:</strong> <%= @recipe.preparation_time %> minutes</p>
      <p class="text-dark"><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes</p>
    </div>
    <div class="col-md-2 text-right">
      <%= form_for @recipe, url: toggle_public_recipe_path(@recipe), method: :patch do |f| %>
        <div class="form-check form-switch">
          <%= f.check_box :public, class: "form-check-input", onchange: "this.form.submit();", checked: @recipe.public? %>
          <label class="form-check-label" for="public">Public</label>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-between my-4">
    <div class="col-md-4">
      <%= link_to 'Generate Shopping List', general_shopping_lists_path, class: 'btn btn-primary' %>
    </div>
    <div class="col-md-2 text-right">
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn btn-secondary' %>
    </div>
  </div>

  <hr class="my-4">

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.quantity * recipe_food.food.price %></td>
<td>
  <div class="button-container">
    <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), class: 'btn btn-info btn-sm mr-2' %>
    <%= button_to 'Delete', recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'btn btn-danger btn-sm inline-form mr-2' %>
  </div>
</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shopping_lists/index.html.erb
<div class="text-center mt-4 mb-4">
  <h1>General Shopping List</h1>
</div>

<div class="shopping-list-summary text-center mt-4 mb-4 d-flex justify-content-center">
  <div class="p-2"><span>Total Food Items:</span><span><%= @total_food_items %></span></div>
  <div class="p-2"><span>Total Price:</span><span><%= @total_price %></span></div>
</div>

<div class="text-center mt-4 mb-4">
  <table class="table table-bordered table-striped" style="width: 500px; margin: auto;">
    <thead class="thead-dark">
      <tr>
        <th>Food Item</th>
        <th>Quantity</th>
        <th>Total Price</th>
      </tr>
    </thead>
    <tbody>
      <% @general_shopping_list.each do |item| %>
        <tr>
          <td><%= item[:name] %></td>
          <td><%= item[:quantity] %></td>
          <td><%= item[:price] * item[:quantity] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>